name: Build and Release OCCD

on:
  push:
    tags:
      - "v*" # 当你推送以 v 开头的标签时（如 v1.0, v1.1）触发
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write  # 必须开启写入权限，否则无法创建 Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AHK2Exe GitHub Action
        uses: MohamedSaidSallam/AHK2Exe-GitHub-Action@v1
        with:
          in: Off-CCD.ahk
          out: Off-CCD.exe
          icon: logo.ico
          ahk_version_tag: v2.0.19

      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # 仅在有标签推送时执行发布
        with:
          files: Off-CCD.exe
          # 自动生成版本说明
          generate_release_notes: true
          # 设置为正式版
          draft: false
          prerelease: false
